name: Caller
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  call-same-repo:
    runs-on: ubuntu-latest
    steps:
    - uses: wechorg/public-repo/.github/workflows/main.yml@main
    
#   call-internal-repo:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: wechorg/internal-repo/.github/workflows/called.yml@main
